---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
# Background
We propose that multilevel regression modeling (MLM) of mixed effects is a highly suitable approach for this class of analytical problems. According to Hox’s textbook on the subject, “multilevel models are designed to analyze variables from different levels simultaneously, using a statistical model that properly includes the various dependencies.”  The MBEB data set used in this study can certainly be viewed as hierarchical; three explanatory variables (gender, maturational status, and consecutive bout number) exist at all levels of exercise intensity, and one single outcome variable (a physiological response) is measured repeatedly for each subject. Initial analysis revealed high levels of intra-class correlation, with clustering of individuals within puberty and gender groups and variables measured at two separate exercise intensities (treatments). Cross-level investigations were required to address our research hypotheses.  

The MLM approach provides several advantages in this setting. By the nature of our experiment, individual observations are longitudinal and therefore could not be considered completely independent. Mixed-effects modeling does not suffer from the restrictions of the independence assumption.  We are also able to draw important conclusions on the condition of interest while accounting for variability within and across participants and Gender × Puberty groups. 

The purpose for using a linear mixed effects model in this study was to effectively capture linear trends of the physiological responses from bout-to-bout, while allowing for between-subject variation through random slopes and intercepts. 

# The Modeling Process.

  Each participant’s average on-transient and off-transient response was calculated by using the mean value of their physiological response over that bout’s associated time period. This method of modeling the mean bout response was intended to facilitate a straightforward set of linear models capable of describing trends in the on-transient and off-transient periods. 

  For each response variable of interest, a linear mixed effects regression was conducted to model the mean on-transient values, and a second linear regression modelled the off-transient means. This dual-model design allows for separate analyses for exercise periods compared to rest periods; treating exercise and rest recovery as uncoupled processes allowed for detailed insight into the on-transient and off-transient responses in each Gender × Puberty group.
  
  The hierarchical nature of the MBEB experiment was represented in each regression model. Test intensity (work rate) was considered the Level 2 grouping factor. Nested within each intensity treatment, participants were labelled by their Level 1 explanatory variables: Gender and Maturational Status. The bout sequence number was used as the repeated measures variable.

  
  In total, 14 mixed effects regression models were generated, including an on- and off-transient model for each of the commonly measured CPET signals: Heart Rate, VO2/kg, VCO2/kg, RQ, VE/kg, RR, and the VE/VCO2 ratio. All MLMs were developed using the Linear Mixed Effects Models ‘lme4’ package (Version 1.1-27.1)  in Rstudio (Version 1.4.1103). Models were fit with restricted maximum likelihood if they failed to converge otherwise.
  
  The final MLMs were chosen through a stepwise variable selection approach that began with the most complex model. Fixed effects considered in the full model were: Gender, a factor with two levels (Male, Female); Maturational status, a factor with two levels (Early, Late); work intensity, a factor with two levels (Low, High); and Bout, a discrete integer predictor in the range of 0 to 5. Any reference to “Bout 0” is equivalent to the baseline measurement (prior to the subject initiating any exercise bouts). Random slope and intercept were allowed in the bout term for each participant ID in order to account for individual variation between subjects. This controlled for innate differences between subjects’ physical fitness levels, psychological motivation, and other non-measured variables. If the full model showed insignificance (p-value > 0.05) in the four-way interaction (Gender*Puberty*Intensity*Bout), the model was re-fit with only three-way interactions. 

